/* Diagram definitions, part 2. */
window.DIAGRAMS = window.DIAGRAMS || {};

/* ---------- 6. Agents, skills and what feeds them ---------- */
DIAGRAMS.agents = {
  type: "flow",
  w: 1100,
  h: 560,
  minW: 820,
  nodeW: 230,
  nodeH: 60,
  label:
    "Map of the main agent, its subagents, skills, rules, hooks and the GitHub agents",
  groups: [
    { x: 40, y: 70, w: 290, h: 190, label: "Skills (how to work)" },
    { x: 40, y: 290, w: 290, h: 190, label: "Rules (what is allowed)" },
    { x: 770, y: 70, w: 290, h: 190, label: "Subagents (fresh context)" },
    {
      x: 770,
      y: 290,
      w: 290,
      h: 250,
      label: "GitHub Actions agents (headless)",
    },
  ],
  nodes: [
    {
      id: "human",
      x: 550,
      y: 50,
      k: "human",
      t: "Human",
      s: "6 slash commands",
    },
    {
      id: "main",
      x: 550,
      y: 270,
      k: "agent",
      w: 240,
      h: 86,
      t: "Main agent",
      s: "Claude Code session\nruns /start /feature /build\n/sync-ui /finish /fix",
    },
    {
      id: "fp",
      x: 185,
      y: 130,
      k: "agent",
      t: "feature-pipeline",
      s: "the 7-step workflow + gates",
    },
    {
      id: "os",
      x: 185,
      y: 210,
      k: "agent",
      t: "openspec-* skills",
      s: "propose · apply · archive\nsync · explore",
    },
    {
      id: "rules",
      x: 185,
      y: 350,
      k: "file",
      t: "CLAUDE.md",
      s: "always loaded: conventions\n+ .claude/rules/* by path",
    },
    {
      id: "cfg",
      x: 185,
      y: 430,
      k: "file",
      t: "openspec/config.yaml",
      s: "risk tier · size · approved line",
    },
    {
      id: "rr",
      x: 915,
      y: 130,
      k: "agent",
      t: "react-reviewer",
      s: "Read/Grep/Glob/Bash\nreports only, runs doctor",
    },
    {
      id: "ce",
      x: 915,
      y: 210,
      k: "agent",
      t: "codebase-explorer",
      s: "Read/Grep/Glob only\nreturns a file map",
    },
    {
      id: "cl",
      x: 915,
      y: 360,
      k: "machine",
      t: "@claude  (claude.yml)",
      s: "mention on issue / PR\n≤ 40 turns, 30 min",
    },
    {
      id: "ap",
      x: 915,
      y: 470,
      k: "machine",
      t: "Autopilot (autopilot.yml)",
      s: "weekday 02:00, ONE approved\nchange, ≤ 80 turns, 45 min",
    },
    {
      id: "hooks",
      x: 550,
      y: 480,
      k: "machine",
      t: "Hooks",
      s: "guard-bash · post-edit\nstop-check",
    },
  ],
  edges: [
    {
      from: "human",
      to: "main",
      label: "commands + gate answers",
      kind: "human",
    },
    { from: "fp", to: "main", fs: "r", ts: "l", tx: -24, label: "loaded" },
    { from: "os", to: "main", fs: "r", ts: "l", tx: -8 },
    { from: "rules", to: "main", fs: "r", ts: "l", tx: 8, label: "loaded" },
    { from: "cfg", to: "main", fs: "r", ts: "l", tx: 24 },
    {
      from: "main",
      to: "rr",
      fs: "r",
      ts: "l",
      fx: -24,
      both: true,
      kind: "loop",
      label: "review", mid: 730, lp: [765, 123],
    },
    {
      from: "main",
      to: "ce",
      fs: "r",
      ts: "l",
      fx: -6,
      both: true,
      kind: "loop",
      label: "research", mid: 730, lp: [765, 203],
    },
    {
      from: "main",
      to: "hooks",
      fs: "b",
      ts: "t",
      fx: -30,
      tx: -30,
      label: "tool calls",
    },
    {
      from: "hooks",
      to: "main",
      fs: "t",
      ts: "b",
      fx: 30,
      tx: 30,
      kind: "fail",
      label: "exit 2 + stderr",
    },
    {
      from: "main",
      to: "cl",
      fs: "r",
      ts: "l",
      fx: 24,
      dash: true,
      label: "same rules", mid: 730, lp: [724, 345], la: "end",
    },
  ],
};

/* ---------- 7. Autopilot decision tree ---------- */
DIAGRAMS.autopilot = {
  type: "flow",
  w: 860,
  h: 1090,
  minW: 620,
  nodeW: 270,
  nodeH: 54,
  label: "Decision tree the nightly autopilot follows",
  nodes: [
    {
      id: "t",
      x: 330,
      y: 30,
      k: "machine",
      pill: true,
      h: 44,
      t: "Cron 02:00 Mon–Fri / manual run",
      s: "",
    },
    {
      id: "c1",
      x: 330,
      y: 110,
      k: "agent",
      t: "List openspec/changes/*",
      s: "with a human-written approved: line",
    },
    {
      id: "d1",
      x: 330,
      y: 205,
      k: "decision",
      w: 290,
      h: 74,
      t: "Eligible one?",
      s: "no open PR · deps archived",
    },
    {
      id: "d2",
      x: 330,
      y: 300,
      k: "decision",
      w: 290,
      h: 70,
      t: "Estimated ≤ 400 lines?",
    },
    {
      id: "d3",
      x: 330,
      y: 395,
      k: "decision",
      w: 290,
      h: 70,
      t: "Open questions answered?",
    },
    {
      id: "d4",
      x: 330,
      y: 490,
      k: "decision",
      w: 290,
      h: 70,
      t: "Screens present in design/?",
    },
    {
      id: "i",
      x: 330,
      y: 580,
      k: "agent",
      t: "Branch autopilot/<change>",
      s: "implement tasks.md per CLAUDE.md",
    },
    {
      id: "d5",
      x: 330,
      y: 670,
      k: "decision",
      w: 290,
      h: 70,
      t: "Needs a new dependency?",
    },
    {
      id: "v",
      x: 330,
      y: 760,
      k: "machine",
      t: "npm run check + test:e2e",
      s: "fix failures",
    },
    {
      id: "d6",
      x: 330,
      y: 855,
      k: "decision",
      w: 290,
      h: 70,
      t: "Green within 3 attempts?",
    },
    {
      id: "d7",
      x: 330,
      y: 950,
      k: "decision",
      w: 290,
      h: 70,
      t: "Real diff ≤ 400 lines?",
    },
    {
      id: "pr",
      x: 330,
      y: 1045,
      k: "gate",
      t: "PR → Gate 2",
      s: "never merges",
    },
    {
      id: "o1",
      x: 710,
      y: 205,
      k: "plain",
      w: 230,
      h: 46,
      t: "Stop — do nothing",
    },
    {
      id: "o2",
      x: 710,
      y: 300,
      k: "human",
      w: 230,
      h: 46,
      t: "Issue: “Split needed”",
    },
    {
      id: "o3",
      x: 710,
      y: 395,
      k: "human",
      w: 230,
      h: 46,
      t: "Issue: “Question”",
    },
    {
      id: "o4",
      x: 710,
      y: 490,
      k: "human",
      w: 230,
      h: 52,
      t: "Issue: “Question”",
      s: "snapshot design via /build",
    },
    {
      id: "o5",
      x: 710,
      y: 670,
      k: "human",
      w: 230,
      h: 46,
      t: "Issue: “Question”",
    },
    {
      id: "o6",
      x: 710,
      y: 855,
      k: "stop",
      w: 230,
      h: 52,
      t: "DRAFT PR",
      s: "explains what is failing",
    },
    {
      id: "o7",
      x: 710,
      y: 950,
      k: "human",
      w: 230,
      h: 46,
      t: "Issue: “Split needed”",
    },
  ],
  edges: [
    { from: "t", to: "c1" },
    { from: "c1", to: "d1" },
    { from: "d1", to: "d2", label: "yes" },
    { from: "d2", to: "d3", label: "yes" },
    { from: "d3", to: "d4", label: "yes" },
    { from: "d4", to: "i", label: "yes" },
    { from: "i", to: "d5" },
    { from: "d5", to: "v", label: "no" },
    { from: "v", to: "d6" },
    { from: "d6", to: "d7", label: "yes" },
    { from: "d7", to: "pr", label: "yes", kind: "ok" },
    { from: "d1", to: "o1", label: "no" },
    { from: "d2", to: "o2", label: "no", kind: "fail" },
    { from: "d3", to: "o3", label: "no", kind: "fail" },
    { from: "d4", to: "o4", label: "no", kind: "fail" },
    { from: "d5", to: "o5", label: "yes", kind: "fail" },
    { from: "d6", to: "o6", label: "no", kind: "fail" },
    { from: "d7", to: "o7", label: "no", kind: "fail" },
  ],
};

/* ---------- 8. The /fix lane ---------- */
DIAGRAMS.fix = {
  type: "flow",
  w: 820,
  h: 900,
  minW: 600,
  nodeW: 260,
  nodeH: 56,
  label: "Flow of the /fix command for bugs in shipped behaviour",
  nodes: [
    {
      id: "b",
      x: 330,
      y: 30,
      k: "human",
      pill: true,
      h: 44,
      t: "/fix <bug report>",
    },
    {
      id: "q",
      x: 330,
      y: 125,
      k: "decision",
      w: 250,
      h: 76,
      t: "Qualifies?",
      s: "all 5 criteria",
    },
    {
      id: "no",
      x: 680,
      y: 125,
      k: "human",
      w: 220,
      h: 50,
      t: "Use /feature instead",
      s: "names the failed criterion",
    },
    {
      id: "rep",
      x: 330,
      y: 225,
      k: "agent",
      t: "Reproduce",
      s: "spec line it breaks + code path\n(codebase-explorer if needed)",
      h: 64,
    },
    {
      id: "br",
      x: 330,
      y: 315,
      k: "agent",
      t: "Branch fix/<slug>",
      s: "from updated default branch",
    },
    {
      id: "red",
      x: 330,
      y: 405,
      k: "stop",
      t: "RED: write a failing test",
      s: "lowest layer: unit > component > e2e",
    },
    {
      id: "dr",
      x: 330,
      y: 505,
      k: "decision",
      w: 270,
      h: 76,
      t: "Fails for the\nreported reason?",
    },
    {
      id: "st",
      x: 680,
      y: 505,
      k: "stop",
      w: 220,
      h: 50,
      t: "Stop",
      s: "tell human what was tried",
    },
    {
      id: "gr",
      x: 330,
      y: 605,
      k: "ok",
      t: "GREEN: smallest fix",
      s: "no refactors / renames",
    },
    {
      id: "gap",
      x: 330,
      y: 695,
      k: "file",
      t: "Spec gap?",
      s: "add scenario to openspec/specs/…",
    },
    {
      id: "ve",
      x: 330,
      y: 785,
      k: "machine",
      t: "npm run check (+ e2e)",
      s: "same 3-attempt rule",
    },
    {
      id: "pr",
      x: 330,
      y: 870,
      k: "gate",
      h: 50,
      t: "PR → Gate 2",
      s: "no Gate 1, no /finish",
    },
  ],
  edges: [
    { from: "b", to: "q" },
    { from: "q", to: "no", label: "no", kind: "fail" },
    { from: "q", to: "rep", label: "yes" },
    { from: "rep", to: "br" },
    { from: "br", to: "red" },
    { from: "red", to: "dr" },
    { from: "dr", to: "st", label: "no", kind: "fail" },
    { from: "dr", to: "gr", label: "yes", kind: "ok" },
    { from: "gr", to: "gap" },
    { from: "gap", to: "ve" },
    { from: "ve", to: "pr", kind: "ok" },
    {
      from: "ve",
      to: "gr",
      fs: "l",
      ts: "l",
      via: [
        [90, 785],
        [90, 605],
      ],
      kind: "fail",
      label: "red → fix",
    },
  ],
};

/* ---------- 9. Design → code ---------- */
DIAGRAMS.tokens = {
  type: "flow",
  w: 1060,
  h: 280,
  minW: 820,
  nodeW: 200,
  nodeH: 60,
  label: "How design tokens and artboards flow one way into code",
  heads: [
    { x: 120, y: 18, label: "claude.ai (source)" },
    { x: 390, y: 18, label: "design/ (by /build, /sync-ui)" },
    { x: 660, y: 18, label: "code" },
    { x: 930, y: 18, label: "uses / checks" },
  ],
  nodes: [
    { id: "ds", x: 120, y: 70, k: "human", t: "Design System", s: "colour · font · radius · space" },
    { id: "tj", x: 390, y: 70, k: "file", t: "design/tokens.json", s: "tokens at last build" },
    { id: "th", x: 660, y: 70, k: "file", t: "@theme  (index.css)", s: "Tailwind 4 styling layer" },
    { id: "cp", x: 930, y: 70, k: "agent", t: "Components", s: "bg-primary — never hex" },
    { id: "cv", x: 120, y: 190, k: "human", t: "Project canvas", s: "page per feature\nartboard per state × width", h: 66 },
    { id: "dc", x: 390, y: 190, k: "file", t: "design/<slug>/", s: "<State>.dc.html + canvas.json" },
    { id: "code", x: 660, y: 190, k: "agent", t: "React screens", s: "match structure, copy, spacing" },
    { id: "shot", x: 930, y: 190, k: "machine", t: "Playwright screenshots", s: "each state × width\nvs artboards (≤ 3 rounds)", h: 66 },
  ],
  edges: [
    { from: "ds", to: "tj", label: "snapshot" },
    { from: "tj", to: "th", label: "sync" },
    { from: "th", to: "cp", label: "tokens" },
    { from: "cv", to: "dc", label: "snapshot" },
    { from: "dc", to: "code", label: "build" },
    { from: "code", to: "shot", label: "capture" },
    { from: "shot", to: "code", fs: "b", ts: "b", via: [[930, 258], [660, 258]], kind: "fail", label: "difference → fix" },
  ],
};

/* ---------- 10. CI: what must be green before a human can merge ---------- */
DIAGRAMS.ci = {
  type: "flow",
  w: 980,
  h: 410,
  minW: 780,
  nodeW: 220,
  nodeH: 60,
  label: "CI jobs and branch protection in front of the merge button",
  nodes: [
    {
      id: "pr",
      x: 90,
      y: 200,
      k: "agent",
      w: 150,
      t: "PR opened",
      s: "or new push",
    },
    {
      id: "ap",
      x: 360,
      y: 55,
      k: "machine",
      t: "approvals",
      s: "no bot-written approved: line",
    },
    {
      id: "q",
      x: 360,
      y: 165,
      k: "machine",
      w: 250,
      h: 86,
      t: "quality",
      s: "typecheck · lint · format\ncoverage floors · build budget\ne2e + axe · doctor (changed)",
    },
    {
      id: "sz",
      x: 360,
      y: 280,
      k: "machine",
      t: "PR size",
      s: "≤ 400 reviewable lines\nor large-pr-approved label",
      h: 64,
    },
    {
      id: "pv",
      x: 360,
      y: 370,
      k: "machine",
      t: "Preview deploy",
      s: "Vercel / Netlify URL",
      h: 52,
    },
    {
      id: "bp",
      x: 650,
      y: 200,
      k: "gate",
      t: "Branch protection",
      s: "all checks green + 1 review\n+ Code Owner review",
      h: 70,
    },
    {
      id: "hm",
      x: 890,
      y: 200,
      k: "human",
      w: 150,
      t: "Human merges",
      s: "Gate 2",
    },
  ],
  edges: [
    { from: "pr", to: "ap", fs: "r", ts: "l", fx: -20, mid: 190 },
    { from: "pr", to: "q", fs: "r", ts: "l", fx: -6, mid: 190 },
    { from: "pr", to: "sz", fs: "r", ts: "l", fx: 8, mid: 190 },
    { from: "pr", to: "pv", fs: "r", ts: "l", fx: 20, mid: 190 },
    { from: "ap", to: "bp", fs: "r", ts: "l", tx: -24, kind: "ok", mid: 520 },
    { from: "q", to: "bp", fs: "r", ts: "l", tx: -8, kind: "ok", mid: 520 },
    { from: "sz", to: "bp", fs: "r", ts: "l", tx: 8, kind: "ok", mid: 520 },
    {
      from: "pv",
      to: "hm",
      fs: "r",
      ts: "b",
      dash: true,
      kind: "human",
      label: "click-through",
    },
    { from: "bp", to: "hm", kind: "ok" },
  ],
};
