/* Diagram definitions. Each key matches a <div data-diagram="..."> in index.html. */
window.DIAGRAMS = window.DIAGRAMS || {};

/* ---------- 1. The whole pipeline, as swimlanes ---------- */
DIAGRAMS.overview = {
  type: "flow",
  w: 1220,
  h: 380,
  minW: 900,
  nodeW: 112,
  nodeH: 66,
  label: "The whole pipeline across three lanes: human, agent, machine",
  lanes: [
    { y: 30, h: 110, k: "human", label: "Human" },
    { y: 145, h: 110, k: "agent", label: "Agent" },
    { y: 260, h: 110, k: "machine", label: "Machine" },
  ],
  heads: [
    "Define",
    "Design",
    "Spec",
    "Gate 1",
    "Implement",
    "Verify",
    "Ship",
    "Gate 2",
    "Learn",
  ].map((label, i) => ({ label, x: 150 + i * 125, y: 20 })),
  nodes: [
    {
      id: "h1",
      x: 150,
      y: 85,
      k: "human",
      t: "Define intent",
      s: "plan mode →\nfeatures.md",
    },
    {
      id: "a2",
      x: 275,
      y: 200,
      k: "agent",
      t: "Design page",
      s: "Claude Design\nartboard / state",
    },
    {
      id: "h2",
      x: 275,
      y: 85,
      k: "human",
      t: "Edit design",
      s: "on claude.ai\n(optional)",
    },
    {
      id: "a3",
      x: 400,
      y: 200,
      k: "agent",
      t: "OpenSpec",
      s: "proposal · specs\ndesign · tasks",
    },
    {
      id: "g1",
      x: 525,
      y: 85,
      k: "gate",
      t: "GATE 1",
      s: "approve brief →\napproved: line",
    },
    {
      id: "a5",
      x: 650,
      y: 200,
      k: "agent",
      t: "Implement",
      s: "task by task\n+ tests",
    },
    {
      id: "m5",
      x: 650,
      y: 315,
      k: "machine",
      t: "Hooks",
      s: "fmt · lint · tsc\ntests · doctor",
    },
    {
      id: "a6",
      x: 775,
      y: 200,
      k: "agent",
      t: "Done gate",
      s: "check · e2e\naxe · screenshots",
    },
    {
      id: "a7",
      x: 900,
      y: 200,
      k: "agent",
      t: "Open PR",
      s: "template filled\n≤ 400 lines",
    },
    {
      id: "m7",
      x: 900,
      y: 315,
      k: "machine",
      t: "CI + preview",
      s: "quality · size\napprovals · URL",
    },
    {
      id: "g2",
      x: 1025,
      y: 85,
      k: "gate",
      t: "GATE 2",
      s: "review PR +\npreview, merge",
    },
    {
      id: "a9",
      x: 1150,
      y: 200,
      k: "agent",
      t: "/finish",
      s: "archive →\nliving specs",
    },
    {
      id: "h9",
      x: 1150,
      y: 85,
      k: "human",
      t: "Learn",
      s: "agree to new\nCLAUDE.md rule",
    },
  ],
  edges: [
    { from: "h1", to: "a2", fs: "b", ts: "l", label: "/feature" },
    { from: "a2", to: "h2", fs: "t", ts: "b", kind: "human" },
    { from: "h2", to: "a3", fs: "r", ts: "t" },
    { from: "a3", to: "g1", fs: "r", ts: "b", label: "/build" },
    { from: "g1", to: "a5", fs: "r", ts: "t", label: '"yes"', kind: "ok" },
    { from: "a5", to: "m5", fs: "b", ts: "t", fx: -22, tx: -22, label: "edit" },
    {
      from: "m5",
      to: "a5",
      fs: "t",
      ts: "b",
      fx: 22,
      tx: 22,
      kind: "fail",
      label: "exit 2",
    },
    { from: "a5", to: "a6", fs: "r", ts: "l" },
    {
      from: "a6",
      to: "a5",
      fs: "t",
      ts: "t",
      tx: 24,
      via: [
        [775, 152],
        [674, 152],
      ],
      kind: "fail",
      label: "red → fix",
      lp: [724, 147],
    },
    { from: "a6", to: "a7", fs: "r", ts: "l", kind: "ok" },
    { from: "a7", to: "m7", fs: "b", ts: "t", label: "push" },
    { from: "m7", to: "g2", fs: "r", ts: "b", tx: -25, kind: "ok" },
    {
      from: "g2",
      to: "a7",
      fs: "l",
      ts: "t",
      kind: "human",
      dash: true,
      label: "comments",
    },
    {
      from: "g2",
      to: "a9",
      fs: "b",
      fx: 25,
      ts: "l",
      via: [[1050, 200]],
      label: "merged",
      kind: "ok",
    },
    { from: "a9", to: "h9", fs: "t", ts: "b", label: "proposes" },
  ],
};

DIAGRAMS.overview.steps = [
  {
    t: "1 · Define (human)",
    d: "You describe the feature in plan mode. The agent writes the behaviour, states (Default, Loading, Empty, Error) and edge cases into features.md, and tech decisions + design tokens into architecture.md. If an API is involved, the contract (Zod / OpenAPI / MSW) is settled first.",
    on: ["h1"],
  },
  {
    t: "2 · Design (agent)",
    d: "/feature looks for the feature’s page on the Claude Design canvas. If it exists it is reused; otherwise the agent draws one artboard per state per width, in the project theme, with real copy. Open decisions go on the canvas as orange sticky notes.",
    on: ["h1", "a2", "h1-a2"],
  },
  {
    t: "3 · You edit the design",
    d: "/feature STOPS here on purpose. The human opens claude.ai and changes anything directly on the canvas. The design is the UI source of truth — the code follows it, never the other way round.",
    on: ["a2", "h2", "a2-h2"],
  },
  {
    t: "4 · Spec (agent)",
    d: "The openspec-propose skill writes proposal.md (risk tier, open questions, non-goals), delta specs, design.md (which artboards) and tasks.md (size estimate first, ordered contract → logic → UI → wiring → e2e). The last line of tasks.md is always “approved: <pending>”.",
    on: ["h2", "a3", "h2-a3"],
  },
  {
    t: "5 · GATE 1 (human)",
    d: "/build re-reads the live design, then sends a one-screen brief: risk, size, decisions with defaults, new deps. Only an explicit “yes” lets the agent replace the last line with “approved: <name>, <date>”. Feedback instead → spec/design updated and the brief is sent again.",
    on: ["a3", "g1", "a3-g1"],
  },
  {
    t: "6 · Implement + hooks (agent ⇄ machine)",
    d: "The design is snapshotted into design/, a branch feat/<change> is created and openspec-apply-change works down tasks.md. Every Edit/Write triggers post-edit.sh (prettier → eslint → tsc). An error returns with exit 2 and the agent fixes it in the same turn.",
    on: ["g1", "a5", "m5", "g1-a5", "a5-m5", "m5-a5"],
  },
  {
    t: "7 · Definition of done (loop)",
    d: "npm run check (typecheck, lint, format, coverage, react-doctor) + npm run test:e2e (with axe) + Playwright screenshots compared with the artboards. Red → fix → re-run. The same failure 3 times → stop and escalate to the human. Never disable a test or rule to go green.",
    on: ["a5", "a6", "a5-a6", "a6-a5"],
  },
  {
    t: "8 · Open the PR (agent)",
    d: "Size check (≤ 400 reviewable lines), then a PR that fills every section of the template — including “Review carefully”, “Safe to skim” and “Decisions I made without asking”. The agent confirms before pushing.",
    on: ["a6", "a7", "a6-a7"],
  },
  {
    t: "9 · CI + preview (machine)",
    d: "CI runs three jobs: approvals (no bot-written approved: line), quality (typecheck, lint, format, coverage, build budget, e2e, doctor) and PR size. The host posts a preview URL.",
    on: ["a7", "m7", "a7-m7"],
  },
  {
    t: "10 · GATE 2 (human)",
    d: "The human clicks through the preview and reads the “Review carefully” lines. Comments go back to the agent, which fixes, replies and pushes. Only a human can merge — merge commands are blocked for the agent.",
    on: ["m7", "g2", "m7-g2", "g2-a7", "a7"],
  },
  {
    t: "11 · Finish + learn",
    d: "/finish archives the OpenSpec change into openspec/specs/ (the living spec), marks the feature shipped, and opens a small bookkeeping PR. If a human corrected the same kind of thing twice, the agent proposes a one-line CLAUDE.md rule — added only if they agree.",
    on: ["g2", "a9", "h9", "g2-a9", "a9-h9"],
  },
];

/* ---------- 2. Life of one change ---------- */
DIAGRAMS.lifecycle = {
  type: "flow",
  w: 1300,
  h: 300,
  minW: 940,
  nodeW: 124,
  nodeH: 58,
  label: "State machine of one OpenSpec change",
  nodes: [
    { id: "idea", x: 80, y: 120, k: "plain", pill: true, t: "Idea", s: "features.md" },
    { id: "spec", x: 270, y: 120, k: "file", t: "Specced", s: "approved: <pending>", w: 140 },
    { id: "appr", x: 460, y: 120, k: "human", t: "Approved", s: "approved: Ana, date", w: 140 },
    { id: "build", x: 650, y: 120, k: "agent", t: "Building", s: "feat/<change>" },
    { id: "pr", x: 840, y: 120, k: "machine", t: "PR open", s: "CI + preview" },
    { id: "merged", x: 1030, y: 120, k: "gate", t: "Merged", s: "by a human only" },
    { id: "arch", x: 1220, y: 120, k: "ok", pill: true, w: 130, t: "Archived", s: "openspec/specs/" },
  ],
  edges: [
    { from: "idea", to: "spec", label: "/feature" },
    { from: "spec", to: "appr", label: "Gate 1", kind: "human" },
    { from: "appr", to: "build", label: "/build" },
    { from: "build", to: "pr", label: "green", kind: "ok" },
    { from: "pr", to: "merged", label: "Gate 2", kind: "human" },
    { from: "merged", to: "arch", label: "/finish", kind: "ok" },
    { id: "spec-loop", from: "spec", to: "spec", fs: "t", ts: "t", fx: -30, tx: 30,
      via: [[240, 50], [300, 50]], kind: "loop", label: "feedback → re-brief", lp: [270, 42] },
    { id: "build-loop", from: "build", to: "build", fs: "t", ts: "t", fx: -30, tx: 30,
      via: [[620, 50], [680, 50]], kind: "loop", label: "self-correct loop", lp: [650, 42] },
    { from: "pr", to: "build", fs: "b", ts: "b", tx: 25, via: [[840, 190], [675, 190]],
      kind: "fail", label: "CI red / review comments" },
    { id: "fix-lane", from: "idea", to: "build", fs: "b", ts: "b", tx: -25,
      via: [[80, 230], [625, 230]], dash: true,
      label: "/fix — bug in shipped behaviour: failing test is the spec (no Gate 1)" },
    { from: "merged", to: "spec", fs: "b", ts: "b", via: [[1030, 272], [270, 272]], dash: true,
      kind: "loop", label: "design edited later → /sync-ui → behaviour change becomes a new change" },
  ],
};

/* ---------- 3. One agent turn: the hook loops ---------- */
DIAGRAMS.turn = {
  type: "flow",
  w: 700,
  h: 760,
  minW: 560,
  nodeW: 220,
  nodeH: 56,
  label: "How hooks feed errors back to the agent within one turn",
  nodes: [
    {
      id: "n1",
      x: 330,
      y: 40,
      k: "agent",
      t: "Claude edits a file",
      s: "Edit / Write tool call",
    },
    {
      id: "n2",
      x: 330,
      y: 130,
      k: "machine",
      t: "post-edit.sh",
      s: "prettier → eslint → tsc --noEmit",
    },
    { id: "d1", x: 330, y: 232, k: "decision", w: 170, h: 72, t: "exit 0?" },
    {
      id: "n3",
      x: 330,
      y: 334,
      k: "agent",
      t: "Next edit / next task",
      s: "tick tasks.md as tests pass",
    },
    {
      id: "n4",
      x: 330,
      y: 424,
      k: "agent",
      t: "Claude tries to end turn",
      s: "Stop event",
    },
    {
      id: "n5",
      x: 330,
      y: 514,
      k: "machine",
      t: "stop-check.sh",
      s: "vitest related + react-doctor",
    },
    { id: "d2", x: 330, y: 616, k: "decision", w: 170, h: 72, t: "exit 0?" },
    {
      id: "n6",
      x: 330,
      y: 718,
      k: "ok",
      t: "Turn ends",
      s: "human sees the result",
    },
    {
      id: "n7",
      x: 585,
      y: 232,
      k: "stop",
      w: 190,
      t: "stderr → Claude",
      s: "exit 2 = fix it now,\nsame turn",
    },
    {
      id: "n8",
      x: 100,
      y: 616,
      k: "stop",
      w: 180,
      h: 70,
      t: "stderr → Claude",
      s: "fix, then retry once\n2nd Stop: let turn end",
    },
  ],
  edges: [
    { from: "n1", to: "n2", label: "PostToolUse" },
    { from: "n2", to: "d1" },
    { from: "d1", to: "n3", label: "yes", kind: "ok" },
    { from: "n3", to: "n4", label: "task done" },
    { from: "n4", to: "n5", label: "Stop hook" },
    { from: "n5", to: "d2" },
    { from: "d2", to: "n6", label: "yes", kind: "ok" },
    { from: "d1", to: "n7", label: "no", kind: "fail" },
    {
      from: "n7",
      to: "n1",
      fs: "t",
      ts: "r",
      kind: "fail",
      label: "agent fixes",
    },
    { from: "d2", to: "n8", label: "no", kind: "fail" },
    {
      from: "n8",
      to: "n1",
      fs: "t",
      ts: "l",
      kind: "fail",
      label: "agent fixes",
    },
  ],
};

/* ---------- 4. Hooks as a sequence ---------- */
DIAGRAMS.hookseq = {
  type: "sequence",
  w: 1150,
  minW: 860,
  step: 32,
  label: "Sequence diagram of the three hooks firing during a /build turn",
  actors: [
    { id: "H", x: 70, k: "human", label: "Human" },
    { id: "C", x: 250, k: "agent", label: "Claude", sub: "main agent" },
    { id: "X", x: 460, k: "plain", label: "Claude Code", sub: "harness" },
    {
      id: "G",
      x: 650,
      k: "machine",
      label: "guard-bash.sh",
      sub: "PreToolUse",
    },
    {
      id: "P",
      x: 820,
      k: "machine",
      label: "post-edit.sh",
      sub: "PostToolUse",
    },
    { id: "S", x: 990, k: "machine", label: "stop-check.sh", sub: "Stop" },
  ],
  msgs: [
    { f: "H", t: "C", label: "/build add-item" },
    { f: "C", t: "X", label: "Bash: git push origin HEAD:master" },
    { f: "X", t: "G", label: "tool_input JSON on stdin" },
    {
      f: "G",
      t: "X",
      label: 'exit 2 · "Blocked: pushing to master"',
      kind: "fail",
    },
    { f: "X", t: "C", label: "call refused, reason shown", kind: "fail" },
    { f: "C", t: "X", label: "Edit ItemForm.tsx" },
    { f: "X", t: "P", label: "file_path of the edit" },
    { f: "P", t: "P", label: "prettier · eslint · tsc" },
    { f: "P", t: "X", label: "exit 2 · TS2322 in ItemForm.tsx", kind: "fail" },
    { f: "X", t: "C", label: "error text fed back", kind: "fail" },
    { f: "C", t: "X", label: "Edit (the fix)" },
    { f: "X", t: "P", label: "PostToolUse again" },
    { f: "P", t: "X", label: "exit 0", kind: "ok" },
    { f: "C", t: "X", label: "done — end turn" },
    { f: "X", t: "S", label: "Stop (stop_hook_active=false)" },
    { f: "S", t: "S", label: "vitest · doctor" },
    { f: "S", t: "X", label: "exit 0", kind: "ok" },
    { f: "X", t: "H", label: "turn ends, summary shown", kind: "ok" },
  ],
};

/* ---------- 5. guard-bash.sh decision flow ---------- */
DIAGRAMS.guard = {
  type: "flow",
  w: 820,
  h: 930,
  minW: 600,
  nodeW: 250,
  nodeH: 54,
  label: "Decision flow of guard-bash.sh",
  nodes: [
    {
      id: "s",
      x: 340,
      y: 30,
      k: "plain",
      pill: true,
      h: 44,
      t: "Bash command arrives",
    },
    {
      id: "p1",
      x: 340,
      y: 105,
      k: "machine",
      t: "Strip heredocs + quoted text",
      s: "but keep text a shell runs (bash -c, eval)",
    },
    {
      id: "p2",
      x: 340,
      y: 185,
      k: "machine",
      t: "Split the chain",
      s: "on && || ; | $( ` {",
    },
    {
      id: "p3",
      x: 340,
      y: 265,
      k: "machine",
      t: "Normalise each part",
      s: "drop VAR=, sudo/env/exec, git -C dir",
    },
    {
      id: "d1",
      x: 340,
      y: 355,
      k: "decision",
      w: 250,
      h: 70,
      t: "gh pr merge ?",
    },
    {
      id: "d2",
      x: 340,
      y: 445,
      k: "decision",
      w: 250,
      h: 70,
      t: "gh api …/merge\nor protection write?",
    },
    { id: "d3", x: 340, y: 535, k: "decision", w: 250, h: 70, t: "git push ?" },
    {
      id: "d4",
      x: 340,
      y: 625,
      k: "decision",
      w: 250,
      h: 70,
      t: "force flag?\n-f  --force*  +ref  --mirror",
    },
    {
      id: "d5",
      x: 340,
      y: 715,
      k: "decision",
      w: 250,
      h: 70,
      t: "destination is\nmain / master?",
    },
    {
      id: "d6",
      x: 340,
      y: 805,
      k: "decision",
      w: 250,
      h: 70,
      t: "on main with no\ntarget, or HEAD?",
    },
    {
      id: "ok",
      x: 340,
      y: 895,
      k: "ok",
      pill: true,
      h: 44,
      t: "exit 0 → command runs",
    },
    {
      id: "b1",
      x: 680,
      y: 355,
      k: "gate",
      w: 220,
      h: 46,
      t: "BLOCK: merging a PR",
    },
    {
      id: "b2",
      x: 680,
      y: 445,
      k: "gate",
      w: 220,
      h: 46,
      t: "BLOCK: merge / protection",
    },
    {
      id: "b4",
      x: 680,
      y: 625,
      k: "gate",
      w: 220,
      h: 46,
      t: "BLOCK: force-pushing",
    },
    {
      id: "b5",
      x: 680,
      y: 715,
      k: "gate",
      w: 220,
      h: 46,
      t: "BLOCK: pushing to master",
    },
    {
      id: "b6",
      x: 680,
      y: 805,
      k: "gate",
      w: 220,
      h: 46,
      t: "BLOCK: implicit push to master",
    },
  ],
  edges: [
    { from: "s", to: "p1" },
    { from: "p1", to: "p2" },
    { from: "p2", to: "p3" },
    { from: "p3", to: "d1", label: "for each part" },
    { from: "d1", to: "d2", label: "no" },
    { from: "d2", to: "d3", label: "no" },
    { from: "d3", to: "d4", label: "yes" },
    { from: "d4", to: "d5", label: "no" },
    { from: "d5", to: "d6", label: "no" },
    { from: "d6", to: "ok", label: "no", kind: "ok" },
    { from: "d1", to: "b1", label: "yes", kind: "fail" },
    { from: "d2", to: "b2", label: "yes", kind: "fail" },
    { from: "d4", to: "b4", label: "yes", kind: "fail" },
    { from: "d5", to: "b5", label: "yes", kind: "fail" },
    { from: "d6", to: "b6", label: "yes", kind: "fail" },
    {
      from: "d3",
      to: "ok",
      fs: "l",
      ts: "l",
      via: [
        [70, 535],
        [70, 895],
      ],
      kind: "ok",
      label: "no → next part",
    },
  ],
};
